apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "devsecops-app.fullname" . }}
  labels:
    {{- include "devsecops-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "devsecops-app.selectorLabels" . | nindent 6 }}
